### ISSUE TITLE
Documentation to-do

### ISSUE THREAD

**Issue by montoyamoraga** [kinectron/kinectron.github.io#4]
- [ ] Upload Coding Train video tutorial.

- [ ] Make coordinate system video for joints.

- [ ] Do your own server video.
